# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    continuationIndentSize: 8
  MaximumLineLength:
    maxLineLength: 140
  NoWildcardImports:
    active: false

naming:
  VariableNaming:
    active: false

style:
  MaxLineLength:
    maxLineLength: 140
  WildcardImport:
    active: false
  MagicNumber:
    active: false

exceptions:
  PrintStackTrace:
    active: false
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: false
